name: EC-CUBE3
title:        EC-CUBE3
tagline:      EC open platform EC-CUBE
# About/contact
author:
  name:       LOCKON CO.,LTD.
  url:        http://www.lockon.co.jp/
pygments: false
markdown: kramdown
kramdown:
  input: GFM
#highlighter: pygments
