name: EC-CUBE 3
title:        EC-CUBE 3 開発ドキュメント
tagline:      EC open platform EC-CUBE
# About/contact
author:
  name:       LOCKON CO.,LTD.
  url:        http://www.lockon.co.jp/
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
gems:
  - jekyll-sitemap
