services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /site
    command:
      - bundle
      - exec
      - jekyll
      - serve
      - --incremental
      - --force_polling
      - --host
      - 0.0.0.0
      - --port
      - "4000"
    volumes:
      - .:/site
      - bundle_cache:/usr/local/bundle
    ports:
      - "4000:4000"

volumes:
  bundle_cache: