version: "3"
services:
  jekyll:
    image: bretfisher/jekyll-serve
    command: [ "bundle", "exec", "jekyll", "serve", "--incremental", "--force_polling", "-H", "0.0.0.0", "-P", "4000" ]
    volumes:
      - .:/site:cached
    ports:
      - '4000:4000'
